name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: sudo apt-get install qmake
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: ls
      run: ls
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: compiled
        path: ./
    - name: ls
      run: ls
